### ISSUE TITLE
Different page structure for credit cards

### ISSUE THREAD

**Issue by mpember** [alexlaverty/python-netbank-scraper#1]
The export links for credit card transactions are located at the bottom of the window, instead of at the top.

Is there any way of identifying and allowing for those elements of the page?

![image](https://user-images.githubusercontent.com/12129928/182176108-fbd28062-e879-417b-9187-6cfdb2669fc8.png)

**Comment by alexlaverty** [comment]
I've pushed a change to support that export button, pull latest from master and give it a go.

**Comment by mpember** [comment]
I'll have a play in the next couple of days.  Thanks.

**Comment by mpember** [comment]
That looks to have done the trick.  Thanks for updating the code so quickly.
